# https://github.com/marketplace/actions/go-release-binaries
name: Release CI

on:
  release:
    types: [created]

jobs:
  release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux,windows,darwin]
        goarch: [amd64, arm64]
        exclude:
          - goarch: arm64
            goos: windows
    steps:
    - uses: actions/checkout@v2
    - uses: wangyoucao577/go-release-action@v1.53
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goversion: "https://dl.google.com/go/go1.23.4.linux-amd64.tar.gz"
        goos: ${{ matrix.goos }}
        goarch: ${{ matrix.goarch }}
        project_path: ./cmd/lxd_exporter
        binary_name: lxd_exporter
        retry: 10
        sha256sum: true
        overwrite: true
        pre_command: go mod tidy
        ldflags:  "-X main.version=${{ github.ref_name }}"
